### ISSUE TITLE
Finish information about user drawer

### ISSUE THREAD

**Issue by Qwebeck** [Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend#408]
Drawer appears after clicking on the user name in the schedule page

Current view:
![image](https://user-images.githubusercontent.com/21079319/166076777-43a3a8fb-a1db-4ed7-b7a2-4571b4be40e6.png)

Expected view:
![image](https://user-images.githubusercontent.com/21079319/166076940-a41df8e2-fa32-47ec-aca2-756fd764183b.png)

Differences:

- [x] download button should be in the right upper corner
- [x] position label should be next to the worker name
- [x] should be normal padding between fields with worker description
- [x] calendar items should be in cells with background

**Comment by net-runner** [comment]
![obraz](https://user-images.githubusercontent.com/40372583/166318573-95019a16-989d-4da5-a21c-df445fe1687a.png)

**Comment by Qwebeck** [comment]
Closed in https://github.com/aI-lab-glider/nurse-scheduling-frontend/pull/419
